import test from 'node:test';
import assert from 'node:assert/strict';
import {handleApi} from '../server/api.mjs';
import {openDatabase} from '../scripts/local-db.mjs';
import {epoch} from '../server/schedule.mjs';
test('guest booking, private links, customer emails, operator isolation and lifecycle',async t=>{
 const DB=openDatabase();t.after(()=>DB.close());const now=epoch('2026-09-16',6);
 const env={DB,GUEST_LINK_SECRET:'local-test-secret-only',CUSTOMER_EMAIL_ENABLED:'true',RESEND_API_KEY:'fake',NOTIFICATION_EMAIL:'mlw903@gmail.com'};
 const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const sent=[];
 globalThis.fetch=async(_,options)=>{sent.push(JSON.parse(options.body));return Response.json({id:'test-email'});};
 const call=async(path,data,token='',operator=false)=>{const r=await handleApi(new Request('https://test.invalid'+path,{method:data?'POST':'GET',headers:{Origin:'https://test.invalid','Content-Type':'application/json',...(token?{'x-booking-access':token}:{}),...(operator?{'oai-authenticated-user-id':'operator','oai-authenticated-user-email':'mlw903@gmail.com'}:{})},...(data?{body:JSON.stringify(data)}:{})}),env,now);return {status:r.status,data:await r.json()};};
 const a=(await call('/api/guest-access',{})).data,b=(await call('/api/guest-access',{})).data;
 const input={id:a.id,zip:'78732',start:epoch('2026-09-17',9),name:'Guest test',email:'customer@example.com',address:'Example address',quantity:5,ready:true};
 assert.equal((await call('/api/bookings',input,a.token)).status,201);
 assert.equal(sent.length,2);assert.deepEqual(sent[1].to,['customer@example.com']);assert.match(sent[1].from,/@512notary.com/);assert.match(sent[1].text,/awaiting confirmation/);
 const link=sent[1].text.match(/https:\/\/512notary.com\/\?booking=[^\s]+/)[0];const token=new URLSearchParams(new URL(link).hash.slice(1)).get('access');
 assert.equal((await call('/api/bookings/'+a.id)).status,401);
 assert.equal((await call('/api/bookings/'+a.id,undefined,b.token)).status,404);
 assert.equal((await call('/api/bookings/'+a.id,undefined,token.slice(0,-2)+'00')).status,401);
 let view=await call('/api/bookings/'+a.id,undefined,token);assert.equal(view.status,200);assert.equal(view.data.booking.owner,undefined);assert.equal(view.data.notifications.length,1);assert.ok(view.data.notifications.every(n=>n.kind.startsWith('customer_')));
 assert.equal((await call('/api/operator/bookings/'+a.id,{action:'confirm',version:1},a.token)).status,401);
 assert.equal((await call('/api/operator/bookings/'+a.id,{action:'confirm',version:1},'',true)).status,200);assert.match(sent.at(-1).text,/confirmed for testing/);
 assert.equal((await call('/api/bookings/'+a.id,{action:'reschedule',version:2,start:epoch('2026-09-17',12)},token)).status,200);
 assert.equal((await call('/api/bookings/'+a.id,undefined,token)).data.booking.status,'pending_confirmation');
 assert.equal((await call('/api/bookings/'+a.id,{action:'cancel',version:3},token)).status,200);
 assert.equal((await DB.prepare('SELECT COUNT(*) n FROM slot_locks').first()).n,0);
 assert.equal((await call('/api/bookings',{...input,id:b.id},a.token)).status,403);
 for(let i=0;i<18;i++)assert.equal((await call('/api/guest-access',{})).status,200);
 assert.equal((await call('/api/guest-access',{})).status,429);
});
